### ISSUE TITLE
Prototyping the components on the auth/dashboard/download page

### ISSUE THREAD

**Issue by Joyidara** [zuri-training/zuri_animation_lib_team97#72]

**Comment by tomisinligali** [comment]
I collaborated with one of my teammate on the created profile drop down created by  Kele-nwa. I  worked the the dropdown 
 by creating and prototyping variants with different states on the profile drop down. Also created and prototyed variants for help button, search animation input field, buttons and content on the Navigation bar


https://www.figma.com/file/YXo3jvJTwsUwWYbpqs9UFF/Project-Zing?node-id=1419%3A8046

**Comment by Kelechim** [comment]
I worked alongside @tomisinligali in creating the profile drop down and prototyping their variants

https://www.figma.com/file/YXo3jvJTwsUwWYbpqs9UFF/Project-Zing?node-id=1419%3A8046
